pipeline {
    agent any
    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('starter_code') { // Mueve a la carpeta correcta
                    sh 'mvn clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('starter_code') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit '**/starter_code/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy stage'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '**/starter_code/target/*.jar', allowEmptyArchive: true
        }
    }
}
